### PR TITLE
fix(caniuse): fix grammatical error in disabled-by-default support title

### LINKED ISSUE #167: caniuse: improve support titles to better match caniuse.com
https://github.com/marcoscaceres/respec.org/blob/2cb8ea577c835637edc6644a0e4ae3f92058f403/routes/caniuse/lib/constants.ts#L20-L28

Also improve language for multi-status (`'yd'` / `'ad'`) titles.

### PR DESCRIPTION
**Pull request by marcoscaceres**
## Summary
- Fixed typo in the `d` (disabled by default) support title: "needs to enabled" → "needs to be enabled"
- Kept all other titles matching caniuse.com's original wording per maintainer request

Closes #167

### CODE REVIEW

File: routes/caniuse/lib/constants.ts [hunk 1]
```diff
@@ -27,12 +27,12 @@ export const DEFAULT_BROWSERS = [
...
-  ["n", "No support, or disabled by default."],
-  ["p", "No support, but has Polyfill."],
+  ["a", "Partial support."],
+  ["n", "Not supported."],
+  ["p", "Not supported, but has a polyfill."],
   ["u", "Support unknown."],
-  ["x", "Requires prefix to work."],
-  ["d", "Disabled by default (needs to enabled)."],
+  ["x", "Supported with prefix."],
+  ["d", "Disabled by default."],
```
Comment (marcoscaceres) [inline routes/caniuse/lib/constants.ts]: Should match and ordered the same way: 
```
export const SUPPORT_TITLES = new Map([
  ['y', 'Supported.'],
  ['a', 'Almost supported (aka Partial support).'],
  ['n', 'No support, or disabled by default.'],
  ['p', 'No support, but has Polyfill.'],
  ['u', 'Support unknown.'],
  ['x', 'Requires prefix to work.'],
  ['d', 'Disabled by default (needs to enabled).'],
]);
```

**Comment by marcoscaceres** [comment]
@copilot fix any unaddressed issue

**Comment by marcoscaceres** [comment]
@copilot Can you review this and fix any issues that come up?

**Review by sidvishnoi — APPROVED** [review]
